# Generated by Django 5.2.16 on 2026-08-10 22:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piscinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parametro', models.CharField(max_length=50, unique=True, verbose_name='Parámetro')),
                ('unidad_medida', models.CharField(blank=True, max_length=20, verbose_name='Unidad')),
                ('rango_normal_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rango_normal_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rango_riesgo_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rango_riesgo_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rango_critico_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rango_critico_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('importancia', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de parámetro',
                'verbose_name_plural': 'Tipos de parámetros',
                'db_table': 'tipos_parametros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de autenticación')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC')),
                ('firmware_version', models.CharField(blank=True, max_length=20, verbose_name='Firmware')),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True, verbose_name='Última conexión')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('sin_conexion', 'Sin conexión')], default='activo', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('geomembrana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='piscinas.geomembrana', verbose_name='Piscina')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo_hardware', models.CharField(max_length=50, unique=True, verbose_name='Código de hardware')),
                ('ubicacion_exacta', models.CharField(blank=True, max_length=255, verbose_name='Ubicación exacta')),
                ('modelo_sensor', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('marca_sensor', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('rango_medicion_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rango_medicion_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('precision_valor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precisión')),
                ('intervalo_lectura_segundos', models.PositiveIntegerField(default=300, verbose_name='Intervalo (s)')),
                ('bateria_nivel_actual', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Batería (%)')),
                ('ultima_calibracion', models.DateField(blank=True, null=True, verbose_name='Última calibración')),
                ('proxima_calibracion', models.DateField(blank=True, null=True, verbose_name='Próxima calibración')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='MAC')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('firmware_version', models.CharField(blank=True, max_length=20, verbose_name='Firmware')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento'), ('averiado', 'Averiado')], default='activo', max_length=15)),
                ('fecha_instalacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('geomembrana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensores', to='piscinas.geomembrana', verbose_name='Piscina')),
                ('tipo_parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensores', to='monitoreo.tipoparametro', verbose_name='Parámetro que mide')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'sensores',
                'ordering': ['geomembrana', 'tipo_parametro'],
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_medida', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
                ('estado_lectura', models.CharField(choices=[('normal', 'Normal'), ('riesgo', 'Riesgo'), ('critico', 'Crítico')], default='normal', max_length=10)),
                ('dentro_rango', models.BooleanField(default=True, verbose_name='Dentro de rango')),
                ('timestamp_lectura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Momento de la lectura')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Recibida en')),
                ('secuencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='N.º de secuencia')),
                ('validada', models.BooleanField(default=False, verbose_name='Validada')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='monitoreo.dispositivo')),
                ('geomembrana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='piscinas.geomembrana')),
                ('usuario_validacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_validadas', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='monitoreo.sensor')),
                ('tipo_parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='monitoreo.tipoparametro')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'db_table': 'lecturas_sensores',
                'ordering': ['-timestamp_lectura'],
                'indexes': [models.Index(fields=['-timestamp_lectura'], name='lecturas_se_timesta_2219b6_idx'), models.Index(fields=['geomembrana', '-timestamp_lectura'], name='lecturas_se_geomemb_b916f8_idx'), models.Index(fields=['sensor', '-timestamp_lectura'], name='lecturas_se_sensor__5a4c83_idx'), models.Index(fields=['estado_lectura'], name='lecturas_se_estado__d1dde5_idx')],
            },
        ),
    ]
