# Generated by Django 5.2.16 on 2026-08-10 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoreo', '0001_initial'),
        ('piscinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('riesgo', 'Riesgo'), ('critico', 'Crítico'), ('sensor', 'Falla de sensor'), ('desconexion', 'Dispositivo sin conexión')], max_length=15, verbose_name='Tipo')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, verbose_name='Severidad')),
                ('valor_que_disparo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
                ('mensaje_alerta', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('reconocida', 'Reconocida'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], default='activa', max_length=15)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reconocimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('accion_tomada', models.TextField(blank=True, verbose_name='Acción tomada')),
                ('geomembrana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='piscinas.geomembrana', verbose_name='Piscina')),
                ('lectura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='monitoreo.lectura')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='monitoreo.sensor')),
                ('tipo_parametro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='monitoreo.tipoparametro')),
                ('usuario_reconocimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_reconocidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['estado', '-fecha_generacion'], name='alertas_estado_f329f3_idx'), models.Index(fields=['geomembrana', 'estado'], name='alertas_geomemb_7d29a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_general', models.CharField(choices=[('optimo', 'Óptimo'), ('riesgo', 'Riesgo'), ('critico', 'Crítico')], max_length=10)),
                ('apta_produccion', models.BooleanField(default=True, verbose_name='Apta para producción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('geomembrana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_estado', to='piscinas.geomembrana')),
            ],
            options={
                'verbose_name': 'Estado del agua',
                'verbose_name_plural': 'Historial de estado del agua',
                'db_table': 'historial_estado_agua',
                'ordering': ['-fecha_evaluacion'],
                'indexes': [models.Index(fields=['geomembrana', '-fecha_evaluacion'], name='historial_e_geomemb_00f339_idx')],
            },
        ),
    ]
