"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import Config, RepositoryEnv, UndefinedValueError, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: la clave NUNCA se versiona. Sale del .env (ya ignorado en
# .gitignore). Si el .env falta, el arranque falla en vez de caer en un default
# inseguro: es preferible un error explicito a un despliegue con clave conocida.
class RepositorioEnvTolerante(RepositoryEnv):
    """
    Lector de .env que ignora un BOM al inicio del archivo.

    PowerShell escribe UTF-8 con BOM por defecto (`>`, `Set-Content -Encoding utf8`).
    python-decouple no lo normaliza, asi que la PRIMERA clave del archivo queda
    como '\ufeffSECRET_KEY' y deja de encontrarse, mientras el resto funciona:
    un fallo silencioso y desconcertante. Todo el equipo trabaja en Windows, asi
    que el lector absorbe el BOM en vez de exigir que cada quien recuerde el
    encoding correcto al editar el archivo.
    """

    def __init__(self, source):
        super().__init__(source)
        self.data = {clave.lstrip('\ufeff'): valor for clave, valor in self.data.items()}


_RUTA_ENV = BASE_DIR / '.env'
if _RUTA_ENV.exists():
    config = Config(RepositorioEnvTolerante(str(_RUTA_ENV)))


def _requerido(clave):
    """
    Lee una variable obligatoria del entorno y falla con un mensaje util.

    :param clave: nombre de la variable
    :return: str con el valor
    :raises ImproperlyConfigured: si no esta definida ni en .env ni en el entorno
    """
    try:
        return config(clave)
    except UndefinedValueError as exc:
        raise ImproperlyConfigured(
            f'Falta la variable {clave}. Definela en {_RUTA_ENV} '
            f'(usa .env.example como plantilla) o como variable de entorno.'
        ) from exc


SECRET_KEY = _requerido('SECRET_KEY')

# SECURITY WARNING: DEBUG=False es el default. Solo el .env de la maquina de
# desarrollo lo activa. Asi un servidor sin .env nunca expone stack traces.
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [h.strip() for h in config('ALLOWED_HOSTS', default='').split(',') if h.strip()]

# Los nodos ESP32 no alcanzan 127.0.0.1: llegan por la IP LAN del servidor, que
# cambia segun la red (router del SENA, hotspot de Windows en 192.168.137.1, o
# el router de campo). Enumerar adaptadores con la libreria estandar no es
# fiable en Windows: socket.gethostbyname_ex() devuelve solo el adaptador
# principal y se salta el del punto de acceso movil.
#
# En DESARROLLO se acepta cualquier Host. Es seguro aqui porque el servidor de
# runserver solo escucha en la LAN local y esta detras del firewall de Windows.
# En PRODUCCION, DEBUG=False y ALLOWED_HOSTS sale del .env con los hosts reales.
if DEBUG:
    ALLOWED_HOSTS = ['*']
elif not ALLOWED_HOSTS:
    raise RuntimeError(
        'Con DEBUG=False, ALLOWED_HOSTS debe definirse en el .env '
        '(lista separada por comas con los hosts del servidor).'
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'rest_framework',

    # Apps
    'apps.core',
    'apps.usuarios',
    'apps.piscinas',
    'apps.monitoreo',
    'apps.alertas',
    'apps.reportes',
    'apps.ia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Bloquea el admin nativo para los roles operativos
    'apps.usuarios.middleware.BloqueoAdminNativoMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.usuario_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='sigmap_agua'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'usuarios.Usuario'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth
LOGIN_URL           = '/auth/login/'
LOGIN_REDIRECT_URL  = '/dashboard/'   # fallback: login_view enruta por rol
LOGOUT_REDIRECT_URL = '/auth/login/'

# ---------------------------------------------------------------------------
# API de ingesta IoT (nodos ESP32)
# ---------------------------------------------------------------------------
# Los endpoints de hardware declaran authentication_classes = [] y autentican
# por token de Dispositivo. Los defaults de abajo aplican al resto de la API.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detallado': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'consola': {
            'class': 'logging.StreamHandler',
            'formatter': 'detallado',
        },
        'archivo_monitoreo': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'monitoreo.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'detallado',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'apps.monitoreo': {
            'handlers': ['consola', 'archivo_monitoreo'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

(BASE_DIR / 'logs').mkdir(exist_ok=True)


# --- Analisis predictivo con Gemini ---------------------------------------
# La clave se obtiene gratis en https://aistudio.google.com/apikey
# Sin ella el modulo de IA sigue accesible pero avisa que no esta configurado:
# ningun otro modulo depende de esto.
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-3.5-flash-lite')
