# Generated by Django 5.2.16 on 2026-08-10 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etapa', models.CharField(max_length=50, unique=True, verbose_name='Etapa')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('dias_duracion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (días)')),
                ('peso_inicial_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso inicial (g)')),
                ('peso_final_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso final (g)')),
                ('densidad_peces_por_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Densidad (peces/m²)')),
                ('rango_temperatura_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rango_temperatura_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rango_ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rango_ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rango_oxigeno_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rango_oxigeno_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rango_turbidez_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rango_turbidez_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etapa de producción',
                'verbose_name_plural': 'Etapas de producción',
                'db_table': 'etapas_produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Geomembrana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_piscina', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo_identificacion', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (m²)')),
                ('profundidad_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Profundidad (m)')),
                ('volumen_agua_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volumen (m³)')),
                ('capacidad_maxima_peces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad máxima')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Instalación')),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Último mantenimiento')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('apta_para_produccion', models.BooleanField(default=True, verbose_name='Apta para producción')),
                ('estado', models.CharField(choices=[('activo', 'Activa'), ('inactivo', 'Inactiva'), ('mantenimiento', 'En mantenimiento')], default='activo', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='geomembranas', to='piscinas.etapaproduccion', verbose_name='Etapa actual')),
            ],
            options={
                'verbose_name': 'Geomembrana',
                'verbose_name_plural': 'Geomembranas',
                'db_table': 'geomembranas',
                'ordering': ['codigo_identificacion'],
            },
        ),
    ]
